protected/models/User.php
<?php

/**
 * This is the model class for table "users".
 *
 * The followings are the available columns in table 'users':
 * @property integer $id
 * @property string $username
 * @property string $password
 * @property string $email
 * @property string $status_text
 * @property integer $online_status_id
 */
class User extends CActiveRecord
{
	/**
	 * @var string password confirmation
	 */
	public $password_confirm;

	/**
	 * @return string the associated database table name
	 */
	public function tableName()
	{
		return 'users';
	}

	/**
	 * @return array validation rules for model attributes.
	 */
	public function rules()
	{
		// NOTE: you should only define rules for those attributes that
		// will receive user inputs.
		return [
			['password, email', 'required'],
			['online_status_id', 'numerical', 'integerOnly' => true],
			['username, password_confirm, email, status_text', 'length', 'max' => 255],
			['password', 'compare', 'compareAttribute' => 'password_confirm', 'on' => 'register'],
			// The following rule is used by search().
			// @todo Please remove those attributes that should not be searched.
			['id, username, password, email, status_text, online_status_id', 'safe', 'on' => 'search'],
		];
	}

	/**
	 * @return array relational rules.
	 */
	public function relations()
	{
		return [
			'online_status' => [self::HAS_ONE, Status::class, ['id' => 'online_status_id']],
			'contacts' => [self::HAS_MANY, Contact::class, ['id' => 'user_id']],
		];
	}

	/**
	 * @return array customized attribute labels (name=>label)
	 */
	public function attributeLabels()
	{
		return [
			'id' => 'ID',
			'username' => 'Username',
			'password' => 'Password',
			'email' => 'Email',
			'status_text' => 'Status Text',
			'online_status_id' => 'Online Status',
		];
	}

	/**
	 * Retrieves a list of models based on the current search/filter conditions.
	 *
	 * Typical usecase:
	 * - Initialize the model fields with values from filter form.
	 * - Execute this method to get CActiveDataProvider instance which will filter
	 * models according to data in model fields.
	 * - Pass data provider to CGridView, CListView or any similar widget.
	 *
	 * @return CActiveDataProvider the data provider that can return the models
	 * based on the search/filter conditions.
	 */
	public function search()
	{
		// @todo Please modify the following code to remove attributes that should not be searched.

		$criteria = new CDbCriteria;

		$criteria->compare('id', $this->id);
		$criteria->compare('username', $this->username, true);
		$criteria->compare('password', $this->password, true);
		$criteria->compare('email', $this->email, true);
		$criteria->compare('status_text', $this->status_text, true);
		$criteria->compare('online_status_id', $this->online_status_id);

		return new CActiveDataProvider($this, [
			'criteria' => $criteria,
		]);
	}

	/**
	 * Returns the static model of the specified AR class.
	 * Please note that you should have this exact method in all your CActiveRecord descendants!
	 * @param string $className active record class name.
	 * @return User the static model class
	 */
	public static function model($className = __CLASS__)
	{
		return parent::model($className);
	}
}

protected/controllers/ContactController.php
<?php

/**
 * Class ContactController
 */
class ContactController extends Controller
{
	/**
	 * @return array action filters
	 */
	public function filters()
	{
		return [
			'accessControl',
		];
	}

	/**
	 * Specifies the access control rules.
	 * This method is used by the 'accessControl' filter.
	 * @return array access control rules
	 */
	public function accessRules()
	{
		return [
			[
				'allow',
				'actions' => ['index', 'list', 'update'],
				'users' => ['@'],
			],
			[
				'deny',
				'users' => ['*'],
			],
		];
	}

	/**
	 * Index & redirect to list
	 */
	public function actionIndex()
	{
		$this->redirect('list');
	}

	/**
	 * Contact list
	 */
	public function actionList()
	{
		$dataProvider = new CActiveDataProvider(Contact::class, [
			'criteria' => [
				'condition' => 'user_id = :user_id',
				'params' => [
					'user_id' => Yii::app()->user->id,
				],
				'with' => [
					'user',
					'contact',
				],
			]
		]);
		$this->render('list', [
			'dataProvider' => $dataProvider,
		]);
	}

	/**
	 * Contact list manipulations action
	 */
	public function actionUpdate()
	{
		switch ($_POST['action']) {
			case 'add':
				$contact = new Contact;
				if (isset($_POST['contact_id'])) {
					$contact->user_id = Yii::app()->user->id;
					$contact->contact_id = (int)$_POST['contact_id'];
					if ($contact->save()) {
						$this->redirect(['/user/view', 'id' => $contact->contact_id]);
					} else {
						throw new CHttpException(500, 'error adding contact');
					}
				}
				break;
			case 'remove':
				$contact = Contact::model()->find('user_id = :user_id AND contact_id = :contact_id', [
					'user_id' => Yii::app()->user->id,
					'contact_id' => (int)$_POST['contact_id'],
				]);
				if (!$contact) {
					throw new CHttpException(500, 'contact not found in your contact list');
				}
				if ($contact->delete()) {
					$this->redirect('/user/view/' . $contact->contact_id);
				} else {
					throw new CHttpException(500, 'error deleting contact');
				}
				break;
			default:
				throw new CHttpException('404', 'action not found');
				break;
		}

	}

}

protected/controllers/UserController.php
<?php

/**
 * Class UserController
 */
class UserController extends Controller
{
	/**
	 * @return array action filters
	 */
	public function filters()
	{
		return [
			'accessControl',
		];
	}

	/**
	 * Specifies the access control rules.
	 * This method is used by the 'accessControl' filter.
	 * @return array access control rules
	 */
	public function accessRules()
	{
		return [
			[
				'allow',
				'actions' => ['index', 'list', 'view', 'register', 'login', 'logout'],
				'users' => ['*'],
			],
			[
				'allow',
				'actions' => ['update'],
				'users' => ['@'],
			],
			[
				'deny',  // deny all users
				'users' => ['*'],
			],
		];
	}

	/**
	 * Displays a particular model.
	 * @param integer $id the ID of the model to be displayed
	 */
	public function actionView($id)
	{
		$model = $this->loadModel($id);

		$this->render('view', [
			'model' => $model,
		]);
	}

	/**
	 * Updates a particular model.
	 * If update is successful, the browser will be redirected to the 'view' page.
	 * @param integer $id the ID of the model to be updated
	 */
	public function actionUpdate()
	{
		$model = $this->loadModel(Yii::app()->user->id);

		if (isset($_POST[User::class])) {
			$model->attributes = $_POST[User::class];
			if ($model->save()) {
				$this->redirect(['view', 'id' => $model->id]);
			}
		}

		$this->render('update', [
			'model' => $model,
		]);
	}

	/**
	 * Lists all models.
	 */
	public function actionList()
	{
		$dataProvider = new CActiveDataProvider(User::class);
		$this->render('list', [
			'dataProvider' => $dataProvider,
		]);
	}

	/**
	 *
	 */
	public function actionIndex()
	{
		$this->redirect('/user/list');
	}

	/**
	 * Returns the data model based on the primary key given in the GET variable.
	 * If the data model is not found, an HTTP exception will be raised.
	 * @param $id
	 * @return User
	 * @throws CHttpException
	 */
	public function loadModel($id)
	{
		$model = User::model()->findByPk($id);
		if ($model === null) {
			throw new CHttpException(404, 'The requested page does not exist.');
		}
		return $model;
	}

	/**
	 * Performs the AJAX validation.
	 * @param CModel the model to be validated
	 */
	protected function performAjaxValidation($model)
	{
		if (isset($_POST['ajax']) && $_POST['ajax'] === 'user-form') {
			echo CActiveForm::validate($model);
			Yii::app()->end();
		}
	}

	/**
	 * Check if user in current user's contact list
	 * @return bool
	 */
	public static function isInMyContactList($contactId)
	{
		return Contact::model()
			->count('user_id = :user_id AND contact_id = :contact_id', [
				'user_id' => Yii::app()->user->id,
				'contact_id' => $contactId,
			]) == 1;
	}

	/**
	 * User registration
	 */
	public function actionRegister()
	{
		$model = new User('register');
		if (isset($_POST[User::class])) {
			$model->attributes = $_POST[User::class];
			if ($model->save()) {
				$this->redirect(['update', 'id' => $model->id]);
			}
		}
		$this->render('register', [
			'model' => $model,
		]);
	}


	/**
	 * Displays the login page
	 */
	public function actionLogin()
	{
		$model = new LoginForm;

		// if it is ajax validation request
		if (isset($_POST['ajax']) && $_POST['ajax'] === 'login-form') {
			echo CActiveForm::validate($model);
			Yii::app()->end();
		}

		// collect user input data
		if (isset($_POST['LoginForm'])) {
			$model->attributes = $_POST['LoginForm'];
			// validate user input and redirect to the previous page if valid
			if ($model->validate() && $model->login()) {
				$this->redirect(Yii::app()->user->returnUrl);
			}
		}
		// display the login form
		$this->render('login', ['model' => $model]);
	}

	/**
	 * Logs out the current user and redirect to homepage.
	 */
	public function actionLogout()
	{
		Yii::app()->user->logout();
		$this->redirect(Yii::app()->homeUrl);
	}
}

protected/views/user/_form.php
<?php
/**
 * @var UserController $this
 * @var User $model
 * @var TbActiveForm $form
 */
$form = $this->beginWidget('booster.widgets.TbActiveForm', [
	'id' => 'user-form',
	'enableAjaxValidation' => false,
]); ?>

<p class="help-block">Fields with <span class="required">*</span> are required.</p>

<?php echo $form->errorSummary($model); ?>

<?php echo $form->textFieldGroup($model, 'username', ['widgetOptions' => ['htmlOptions' => ['class' => 'span5', 'maxlength' => 255]]]); ?>

<?php echo $form->passwordFieldGroup($model, 'password', ['widgetOptions' => ['htmlOptions' => ['class' => 'span5', 'maxlength' => 255]]]); ?>

<?php echo $form->textFieldGroup($model, 'email', ['widgetOptions' => ['htmlOptions' => ['class' => 'span5', 'maxlength' => 255]]]); ?>

<?php echo $form->textFieldGroup($model, 'status_text', ['widgetOptions' => ['htmlOptions' => ['class' => 'span5', 'maxlength' => 255]]]); ?>

<?php echo $form->dropDownListGroup($model, 'online_status_id', [
	'widgetOptions' => [
		'htmlOptions' => ['class' => 'span5'],
		'data' => CHtml::listData(Status::model()->findAll(), 'id', 'name'),
	]
]); ?>

<div class="form-actions">
	<?php $this->widget('booster.widgets.TbButton', [
		'buttonType' => 'submit',
		'context' => 'primary',
		'label' => $model->isNewRecord ? 'Register' : 'Save',
	]); ?>
</div>

<?php $this->endWidget(); ?>

protected/views/user/_register_form.php
<?php
/**
 * @var UserController $this
 * @var User $model
 * @var TbActiveForm $form
 */
$form = $this->beginWidget('booster.widgets.TbActiveForm', [
	'id' => 'user-form',
	'enableAjaxValidation' => false,
]); ?>

<p class="help-block">Fields with <span class="required">*</span> are required.</p>

<?php echo $form->errorSummary($model); ?>

<?php echo $form->textFieldGroup($model, 'username', ['widgetOptions' => ['htmlOptions' => ['class' => 'span5', 'maxlength' => 255]]]); ?>

<?php echo $form->passwordFieldGroup($model, 'password', ['widgetOptions' => ['htmlOptions' => ['class' => 'span5', 'maxlength' => 255]]]); ?>

<?php echo $form->passwordFieldGroup($model, 'password_confirm', ['widgetOptions' => ['htmlOptions' => ['class' => 'span5', 'maxlength' => 255]]]); ?>

<?php echo $form->textFieldGroup($model, 'email', ['widgetOptions' => ['htmlOptions' => ['class' => 'span5', 'maxlength' => 255]]]); ?>

<?php echo $form->textFieldGroup($model, 'status_text', ['widgetOptions' => ['htmlOptions' => ['class' => 'span5', 'maxlength' => 255]]]); ?>

<div class="form-actions">
	<?php $this->widget('booster.widgets.TbButton', [
		'buttonType' => 'submit',
		'context' => 'primary',
		'label' => 'Register',
	]); ?>
</div>

<?php $this->endWidget(); ?>

protected/views/user/list.php
<?php
/**
 * @var UserController $this
 * @var CActiveDataProvider $dataProvider
 */

$this->breadcrumbs = [
	'Users',
];
?>

<h1>Users</h1>

<?php $this->widget('booster.widgets.TbGridView', [
	'dataProvider' => $dataProvider,
	'template' => '{items}',
	'columns' => [
		[
			'name' => 'username',
			'value' => function ($data) {
				return CHtml::link($data['username'], '/user/view/' . $data['id']);
			},
			'type' => 'html',
		],

	],
]);

protected/views/user/login.php
<?php
/* @var $this UserController */
/* @var $model LoginForm */
/* @var $form TbActiveForm */

$this->pageTitle = Yii::app()->name . ' - Login';
$this->breadcrumbs = [
	'Login',
];
?>

<h1>Login</h1>

<p>Please fill out the following form with your login credentials:</p>

<?php $form = $this->beginWidget('booster.widgets.TbActiveForm', [
	'id' => 'login-form',
	'enableClientValidation' => true,
	'clientOptions' => [
		'validateOnSubmit' => true,
	],
]); ?>

<p class="help-block">Fields with <span class="required">*</span> are required.</p>

<?php echo $form->errorSummary($model); ?>

<?php echo $form->textFieldGroup($model, 'email'); ?>

<?php echo $form->passwordFieldGroup($model, 'password'); ?>

<?php echo $form->checkboxGroup($model, 'rememberMe'); ?>

<div class="form-actions">
	<?php $this->widget('booster.widgets.TbButton', [
		'buttonType' => 'submit',
		'context' => 'primary',
		'label' => 'Login',
	]); ?>
</div>

<?php $this->endWidget(); ?>

protected/views/user/register.php
<?php
$this->breadcrumbs = [
	'Users' => ['/user'],
	'Register',
];

?>

<h1>Register new user</h1>

<?php echo $this->renderPartial('_register_form', ['model' => $model]); ?>

protected/views/user/update.php
<?php
$this->breadcrumbs = [
	'Users' => ['/user'],
	$model->id => ['view', 'id' => $model->id],
	'Update',
];

?>

<h1>Update User <?php echo $model->id; ?></h1>

<?php echo $this->renderPartial('_form', ['model' => $model]); ?>

protected/views/user/view.php
<?php
/**
 * @var UserController $this
 * @var User $model
 */
$this->breadcrumbs = [
	'Users' => ['/user'],
	$model->id,
];

?>

<h1>View User #<?php echo $model->id; ?></h1>
<?php
// if I am on myself's page
if (Yii::app()->user->id != $model->id) {
	echo CHtml::form('/contact/update');
	echo CHtml::hiddenField('contact_id', $model->id);
	if (!$this::isInMyContactList($model->id)) {
		echo CHtml::hiddenField('action', 'add');
		echo CHtml::submitButton('Add') . ' from my contact list';

	} else {
		echo CHtml::hiddenField('action', 'remove');
		echo CHtml::submitButton('Remove') . ' to my contact list';
		echo '<br>';
		echo CHtml::link('Write a message', '/message/user/' . $model->id) . ' to user';
	}
	echo CHtml::endForm();
} else {
	echo '<div class="alert alert-info" role="alert">it`s me!<br>' . CHtml::link('edit', '/user/update/') . ' my profile</div>';
}
?>

<?php $this->widget('booster.widgets.TbDetailView', [
	'data' => $model,
	'attributes' => [
		'id',
		'username',
//		'password',
		'email',
		'status_text',
		[
			'name' => 'online_status_id',
			'value' => function ($data) {
				return $data->online_status->name;
			}
		],
		[
			'name' => 'Unread count',
			'value' => function ($data) {
				return Message::unreadCount($data->id);
			}
		]
	],
]); ?>