protected/controllers/ContactController.php
<?php

/**
 * Class ContactController
 */
class ContactController extends Controller
{
	/**
	 * @return array action filters
	 */
	public function filters()
	{
		return [
			'accessControl',
		];
	}

	/**
	 * Specifies the access control rules.
	 * This method is used by the 'accessControl' filter.
	 * @return array access control rules
	 */
	public function accessRules()
	{
		return [
			[
				'allow',
				'actions' => ['index', 'list', 'update'],
				'users' => ['@'],
			],
			[
				'deny',
				'users' => ['*'],
			],
		];
	}

	/**
	 * Index & redirect to list
	 */
	public function actionIndex()
	{
		$this->redirect('list');
	}

	/**
	 * Contact list
	 */
	public function actionList()
	{
		$dataProvider = new CActiveDataProvider(Contact::class, [
			'criteria' => [
				'condition' => 'user_id = :user_id',
				'params' => [
					'user_id' => Yii::app()->user->id,
				],
				'with' => [
					'user',
					'contact',
				],
			]
		]);
		$this->render('list', [
			'dataProvider' => $dataProvider,
		]);
	}

	/**
	 * Contact list manipulations action
	 */
	public function actionUpdate()
	{
		switch ($_POST['action']) {
			case 'add':
				$contact = new Contact;
				if (isset($_POST['contact_id'])) {
					$contact->user_id = Yii::app()->user->id;
					$contact->contact_id = (int)$_POST['contact_id'];
					if ($contact->save()) {
						$this->redirect(['/user/view', 'id' => $contact->contact_id]);
					} else {
						throw new CHttpException(500, 'error adding contact');
					}
				}
				break;
			case 'remove':
				$contact = Contact::model()->find('user_id = :user_id AND contact_id = :contact_id', [
					'user_id' => Yii::app()->user->id,
					'contact_id' => (int)$_POST['contact_id'],
				]);
				if (!$contact) {
					throw new CHttpException(500, 'contact not found in your contact list');
				}
				if ($contact->delete()) {
					$this->redirect('/user/view/' . $contact->contact_id);
				} else {
					throw new CHttpException(500, 'error deleting contact');
				}
				break;
			default:
				throw new CHttpException('404', 'action not found');
				break;
		}

	}

}

protected/controllers/MessageController.php
<?php

/**
 * Class MessageController
 */
class MessageController extends Controller
{
	/**
	 * @return array action filters
	 */
	public function filters()
	{
		return [
			'accessControl',
		];
	}

	/**
	 * Specifies the access control rules.
	 * This method is used by the 'accessControl' filter.
	 * @return array access control rules
	 */
	public function accessRules()
	{
		return [
			[
				'allow',
				'actions' => ['index', 'user', 'list', 'view'],
				'users' => ['@'],
			],
			[
				'deny',
				'users' => ['*'],
			],
		];
	}

	/**
	 * Index & redirect to list
	 */
	public function actionIndex()
	{
		$this->redirect('list');
	}

	/**
	 * Send message to user
	 */
	public function actionUser($id)
	{
		if (isset($id)) {
			// oops!
			Yii::import('application.controllers.UserController');
			$isInMyContactList = UserController::isInMyContactList((int)$id);

			$message = new Message;
			if (isset($_POST[Message::class]) && $isInMyContactList) {
				$message->attributes = $_POST[Message::class];
				$message->sender_id = Yii::app()->user->id;
				$message->recipient_id = (int)$id;
				if ($message->save()) {
					$this->redirect('/message/');
				}
			}

			$this->render('user', [
				'model' => $message,
				'inMyContactList' => $isInMyContactList,
			]);
		} else {
			throw new CHttpException(404, 'recipient is not specified');
		}
	}

	/**
	 * Messages list
	 */
	public function actionList()
	{
		$messages = Message::listUsersMessages(Yii::app()->user->id);

		$this->render('list', [
			'messages' => $messages
		]);
	}

	/**
	 * View message
	 */
	public function actionView($id)
	{
		$message = Message::model()->findByPk($id);

		// cant read message that's not mine
		if (!$message->isRelatedToUser(Yii::app()->user->id)) {
			throw new CHttpException(403, 'The message you`re trying to view is not yours');
		}

		// only recipient can mark message as viewed
		if (!$message->isFromUser(Yii::app()->user->id)) {
			$message->markAsRead();
		}

		$this->render('view', [
			'message' => $message,
		]);
	}
}

protected/controllers/UserController.php
<?php

/**
 * Class UserController
 */
class UserController extends Controller
{
	/**
	 * @return array action filters
	 */
	public function filters()
	{
		return [
			'accessControl',
		];
	}

	/**
	 * Specifies the access control rules.
	 * This method is used by the 'accessControl' filter.
	 * @return array access control rules
	 */
	public function accessRules()
	{
		return [
			[
				'allow',
				'actions' => ['index', 'list', 'view', 'register', 'login', 'logout'],
				'users' => ['*'],
			],
			[
				'allow',
				'actions' => ['update'],
				'users' => ['@'],
			],
			[
				'deny',  // deny all users
				'users' => ['*'],
			],
		];
	}

	/**
	 * Displays a particular model.
	 * @param integer $id the ID of the model to be displayed
	 */
	public function actionView($id)
	{
		$model = $this->loadModel($id);

		$this->render('view', [
			'model' => $model,
		]);
	}

	/**
	 * Updates a particular model.
	 * If update is successful, the browser will be redirected to the 'view' page.
	 * @param integer $id the ID of the model to be updated
	 */
	public function actionUpdate()
	{
		$model = $this->loadModel(Yii::app()->user->id);

		if (isset($_POST[User::class])) {
			$model->attributes = $_POST[User::class];
			if ($model->save()) {
				$this->redirect(['view', 'id' => $model->id]);
			}
		}

		$this->render('update', [
			'model' => $model,
		]);
	}

	/**
	 * Lists all models.
	 */
	public function actionList()
	{
		$dataProvider = new CActiveDataProvider(User::class);
		$this->render('list', [
			'dataProvider' => $dataProvider,
		]);
	}

	/**
	 *
	 */
	public function actionIndex()
	{
		$this->redirect('/user/list');
	}

	/**
	 * Returns the data model based on the primary key given in the GET variable.
	 * If the data model is not found, an HTTP exception will be raised.
	 * @param $id
	 * @return User
	 * @throws CHttpException
	 */
	public function loadModel($id)
	{
		$model = User::model()->findByPk($id);
		if ($model === null) {
			throw new CHttpException(404, 'The requested page does not exist.');
		}
		return $model;
	}

	/**
	 * Performs the AJAX validation.
	 * @param CModel the model to be validated
	 */
	protected function performAjaxValidation($model)
	{
		if (isset($_POST['ajax']) && $_POST['ajax'] === 'user-form') {
			echo CActiveForm::validate($model);
			Yii::app()->end();
		}
	}

	/**
	 * Check if user in current user's contact list
	 * @return bool
	 */
	public static function isInMyContactList($contactId)
	{
		return Contact::model()
			->count('user_id = :user_id AND contact_id = :contact_id', [
				'user_id' => Yii::app()->user->id,
				'contact_id' => $contactId,
			]) == 1;
	}

	/**
	 * User registration
	 */
	public function actionRegister()
	{
		$model = new User('register');
		if (isset($_POST[User::class])) {
			$model->attributes = $_POST[User::class];
			if ($model->save()) {
				$this->redirect(['update', 'id' => $model->id]);
			}
		}
		$this->render('register', [
			'model' => $model,
		]);
	}


	/**
	 * Displays the login page
	 */
	public function actionLogin()
	{
		$model = new LoginForm;

		// if it is ajax validation request
		if (isset($_POST['ajax']) && $_POST['ajax'] === 'login-form') {
			echo CActiveForm::validate($model);
			Yii::app()->end();
		}

		// collect user input data
		if (isset($_POST['LoginForm'])) {
			$model->attributes = $_POST['LoginForm'];
			// validate user input and redirect to the previous page if valid
			if ($model->validate() && $model->login()) {
				$this->redirect(Yii::app()->user->returnUrl);
			}
		}
		// display the login form
		$this->render('login', ['model' => $model]);
	}

	/**
	 * Logs out the current user and redirect to homepage.
	 */
	public function actionLogout()
	{
		Yii::app()->user->logout();
		$this->redirect(Yii::app()->homeUrl);
	}
}

protected/views/layouts/bootstrap/_nav.php
<?php
/**
 * @var Controller $this
 */

$this->widget(
	'booster.widgets.TbNavbar',
	[
		'type' => 'inverse',
		'brand' => Yii::app()->params['name'],
		'brandUrl' => '/',
		'collapse' => true,
		'fixed' => false,
		'items' => [
			[
				'class' => 'booster.widgets.TbMenu',
				'type' => 'navbar',
				'encodeLabel' => false,
				'items' => [
					[
						'label' => 'Home',
						'url' => ['/site/index'],
					],
					[
						'label' => 'Users',
						'url' => ['/user/list'],
					],
					[
						'label' => 'Contact list',
						'url' => ['/contact/list'],
						'visible' => !Yii::app()->user->isGuest,
					],
					[
						'label' => 'Message list <span class="badge" title="Unread messages">' . CHtml::encode(Message::unreadCount(Yii::app()->user->id)) . '</span>',
						'url' => ['/message/list'],
						'visible' => !Yii::app()->user->isGuest,
					],
				],
			],
			[
				'class' => 'booster.widgets.TbMenu',
				'type' => 'navbar',
				'htmlOptions' => [
					'class' => 'pull-right',
				],
				'items' => [
					[
						'label' => 'Login',
						'url' => [Yii::app()->user->loginUrl],
						'visible' => Yii::app()->user->isGuest,
					],
					[
						'label' => 'Register',
						'url' => ['/user/register'],
						'visible' => Yii::app()->user->isGuest,
					],
					[
						'label' => 'User ' . Yii::app()->user->name,
						'visible' => !Yii::app()->user->isGuest,
						'items' => [
							[
								'label' => 'Edit profile',
								'url' => ['/user/update'],
							],
							[
								'label' => 'Logout',
								'url' => ['/user/logout'],
							],
						],
					],
				],
			]
		],
	]
);

protected/views/layouts/bootstrap/main.php
<?php
/**
 * @var Controller $this
 * @var string $content
 */
?>
<!DOCTYPE html>
<!--[if lt IE 7]>
<html class="no-js lt-ie9 lt-ie8 lt-ie7"> <![endif]-->
<!--[if IE 7]>
<html class="no-js lt-ie9 lt-ie8"> <![endif]-->
<!--[if IE 8]>
<html class="no-js lt-ie9"> <![endif]-->
<!--[if gt IE 8]><!-->
<html class="no-js"> <!--<![endif]-->
<head>
	<meta charset="utf-8">
	<meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
	<meta name="viewport" content="width=device-width,initial-scale=1">
	<title><?= CHtml::encode($this->pageTitle); ?></title>
</head>

<body>
<!-- NAVIGATION BEGIN -->
<?php $this->renderPartial('//layouts/bootstrap/_nav'); ?>
<!-- NAVIGATION END -->

<!-- CONTENT WRAPPER BEGIN -->
<div class="container">
	<?php if (isset($this->breadcrumbs)): ?>
		<?php $this->widget(
			'booster.widgets.TbBreadcrumbs',
			[
				'links' => $this->breadcrumbs,
			]
		); ?>
	<?php endif ?>

	<div class="row">
<!--		<div class="col-sm-2 sidebar">
			<?php /*$this->widget('booster.widgets.TbMenu', [
				'type' => 'list',
				'items' => $this->menu,
			]); */?>
		</div>
		<div class="col-sm-10">-->
			<!-- CONTENT BEGIN -->
			<?= $content; ?>
			<!-- CONTENT END -->
<!--		</div>-->

	</div>

	<div class="row">
		<hr/>
		<footer>
			Copyright &copy; <?php echo date('Y'); ?> by My Company.<br/>
			All Rights Reserved.<br/>
			<?= Yii::powered(); ?>
		</footer>
	</div>

</div>
<!-- CONTENT WRAPPER END -->

</body>
</html>